### ISSUE TITLE
RIP

### ISSUE THREAD

**Issue by ElliotGluck** [mcklyde/SynergisticGism#5]
Mark as deprecated because lucas fucked up and now you won’t get certified

**Comment by mcklyde** [comment]
Clearly you have no experience in real world scenarios, they aren't my crush! I'm sure they won't leave me on read 😞 <sup>*pls dont leave me on read*</sup>

**Comment by lucasxz** [comment]
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo ok
